name: counter_mobx
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.3.0+1 # Provides annotations to use in store (MobX) classes
  flutter_mobx: ^2.2.0+2  # Widgets that helps to implement MobX as state manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.0+1 # To generate code with annotations from mobx package
  build_runner: ^2.4.8
  

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  