// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmosrNANLJvR5p0nWhMDZGbcpiskICBW0',
    appId: '1:754449649537:web:909e17d434e8124d9a2280',
    messagingSenderId: '754449649537',
    projectId: 'fir-app-88996',
    authDomain: 'fir-app-88996.firebaseapp.com',
    storageBucket: 'fir-app-88996.appspot.com',
    measurementId: 'G-76PFNK2327',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv21NXgl8mqdXWNOY3OQN-day-LQVx2X8',
    appId: '1:754449649537:android:80319559dd7735929a2280',
    messagingSenderId: '754449649537',
    projectId: 'fir-app-88996',
    storageBucket: 'fir-app-88996.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAnC9GF2OHqZoAWUAVEdtsKxmcnLH_bTQ',
    appId: '1:754449649537:ios:92999009d322b5609a2280',
    messagingSenderId: '754449649537',
    projectId: 'fir-app-88996',
    storageBucket: 'fir-app-88996.appspot.com',
    iosBundleId: 'dev.enrico.firebaseapp',
  );

}