name: testes_app
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  http: ^1.1.1
  mockito: ^5.4.3
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^2.1.0
  test: ^1.24.0
