name: bloc_intro_app_with_package_with_package
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2  # pattern - bloc - para utilizar na classe do bloc
  flutter_bloc: ^8.1.3 # Widgets que facilitarao o consumo do bloc (substituindo o StreamBuilder por BlocBuilder, por exemplo)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
