// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRYUkdhI7jwqg7Xj7pfHB4ZcMXYTNAto8',
    appId: '1:179877687059:web:772708f4be545fd3e834e6',
    messagingSenderId: '179877687059',
    projectId: 'chatappflutter-be110',
    authDomain: 'chatappflutter-be110.firebaseapp.com',
    storageBucket: 'chatappflutter-be110.appspot.com',
    measurementId: 'G-L8FCXLYRLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_5HuMq5BbJGyj8eDoRQwqKrs2bWAwxMk',
    appId: '1:179877687059:android:9c9611a2c8865c01e834e6',
    messagingSenderId: '179877687059',
    projectId: 'chatappflutter-be110',
    storageBucket: 'chatappflutter-be110.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApz8gCN6CX56IvfsgP9v2D2OWBbZnGkC4',
    appId: '1:179877687059:ios:238823cd4257384de834e6',
    messagingSenderId: '179877687059',
    projectId: 'chatappflutter-be110',
    storageBucket: 'chatappflutter-be110.appspot.com',
    androidClientId: '179877687059-bh81me7uksemr6823m5vangjm364t536.apps.googleusercontent.com',
    iosClientId: '179877687059-o7gaef1gsiiqijrnqggvsv27i5dn2tvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatOnlineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApz8gCN6CX56IvfsgP9v2D2OWBbZnGkC4',
    appId: '1:179877687059:ios:95c50f75ecedd229e834e6',
    messagingSenderId: '179877687059',
    projectId: 'chatappflutter-be110',
    storageBucket: 'chatappflutter-be110.appspot.com',
    androidClientId: '179877687059-bh81me7uksemr6823m5vangjm364t536.apps.googleusercontent.com',
    iosClientId: '179877687059-l2nen459751ctnc96v632e69ajau7l04.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatOnlineApp.RunnerTests',
  );
}
