name: firebase_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.1
  firebase_analytics: ^11.1.0
  firebase_core: ^3.1.0
  firebase_crashlytics: ^4.0.2
  firebase_remote_config: ^5.0.2
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
