name: favorites_yt_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  extension_google_sign_in_as_googleapis_auth: ^2.0.13
  flutter:
    sdk: flutter
  google_sign_in: ^6.3.0
  googleapis: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
