// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD69J5iJIW2cepFe86mlE_hsRlpNzt2wOY',
    appId: '1:183986218136:web:3e31410b1c76297d149ced',
    messagingSenderId: '183986218136',
    projectId: 'virtualstore-daf33',
    authDomain: 'virtualstore-daf33.firebaseapp.com',
    storageBucket: 'virtualstore-daf33.appspot.com',
    measurementId: 'G-W51QZNZCNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6V82PEn1qgcjEUp187pzgZBg-M81c-mI',
    appId: '1:183986218136:android:58892927caabec55149ced',
    messagingSenderId: '183986218136',
    projectId: 'virtualstore-daf33',
    storageBucket: 'virtualstore-daf33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcZi5Nzc9CeeiP9yXBOwyt7fK5RY6-IP0',
    appId: '1:183986218136:ios:d609a1de6656f282149ced',
    messagingSenderId: '183986218136',
    projectId: 'virtualstore-daf33',
    storageBucket: 'virtualstore-daf33.appspot.com',
    iosBundleId: 'com.example.virtualStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcZi5Nzc9CeeiP9yXBOwyt7fK5RY6-IP0',
    appId: '1:183986218136:ios:6690ae4db12d2862149ced',
    messagingSenderId: '183986218136',
    projectId: 'virtualstore-daf33',
    storageBucket: 'virtualstore-daf33.appspot.com',
    iosBundleId: 'com.example.virtualStore.RunnerTests',
  );
}
